### Get all users
GET http://localhost:8080/api/users


### Create user
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "firstName": "Marko",
  "lastName": "Markovic",
  "email": "marko@example.com"
}